### ISSUE TITLE
Fly Execute fails with gzip: invalid magic

### ISSUE THREAD

**Issue by andrew-edgar** [concourse/fly#102]
I am with the Diego development team and when we try to execute our inigo tests remotely from several machines we quite regularly (especially from my machine in Canada) get the following error when doing the upload step in the fly execute ...

```
executing build 150754
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0
curl: (18) transfer closed with outstanding read data remaining
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
exit status 2
100 42.1M    0 42.1M    0     0   303k      0 --:--:--  0:02:22 --:--:--  206k
failed

upload request failed: Put https://diego.ci.cf-app.com/api/v1/pipes/3df3e884-3b6c-40ba-6800-e04b061e2fc5: EOF
```

The run-inigo script we use is as follows ...

```
#!/bin/bash

set -e

scripts_path=./$(dirname $0)
eval $($scripts_path/get_paths.sh)

echo "checking code for compilation errors..."

pushd $DIEGO_RELEASE_DIR/src/code.cloudfoundry.org/inigo > /dev/null
  for pkg in `find . -maxdepth 1 -type d ! -path . -not -path '*/\.*'`; do
    echo $pkg
    go test -c ./${pkg} > /dev/null
  done
popd > /dev/null

echo "compilation done"

if [ -n "${DIEGO_CI_TARGET}" ]; then
  target="-t ${DIEGO_CI_TARGET}"
else
  target="-t local"
fi

if [ -z "${USE_GARDEN_RUNC}" ]; then
  fly ${target} execute -p -x \
    -c $DIEGO_RELEASE_DIR/scripts/ci/run_inigo_glinux.build.yml \
    -i diego-release=$PWD \
    -i garden-linux-release=$HOME/workspace/garden-linux-release \
    -- "$@"
else
  fly ${target} execute -p -x \
    -c $DIEGO_RELEASE_DIR/scripts/ci/run_inigo_grunc.build.yml \
    -i diego-release=$PWD \
    -i garden-runc-release=$HOME/workspace/garden-runc-release \
    -- "$@"
fi
```

The run_inigo_grunc.build.yml is as follows:

```

platform: linux

image: docker:///cloudfoundry/inigo-ci

inputs:
- name: diego-release
- name: garden-runc-release

params:
  GINKGO_PARALLEL: "true" # we check for the literal string "true" in the run_inigo script
  DEFAULT_EVENTUALLY_TIMEOUT:
  INIGO_REPEAT_COUNT: 1
  SKIP_PACKAGES:
  SKIP_REGEX:
  USE_SQL:
  USE_GARDEN_RUNC: "true"

run:
  path: diego-release/scripts/ci/run_inigo
```

This does seem to occur mostly from my slower upload connection but we have also seen this happen from machines in the Pivotal SF office.

**Comment by andrew-edgar** [comment]
Any progress on this?  Still causes issues as unable to run tests remotely on Concourse!

**Comment by vito** [comment]
I'm not really sure where to start with this one to be honest. Diagnosing network issues like this tends to be very open-ended. It might just not be stable enough given the physics of your network layout, or it could be something going wrong with your infrastructure's configuration, which we don't really have any way of knowing anything about.

**Comment by jaresty** [comment]
@vito We are seeing this issue too in runtime-ci.  Come by if you would like a demonstration.

**Comment by youreddy** [comment]
@vito Our team, hotSQL is also seeing this issue. Any new ideas as to what's going on?

**Comment by julian-hj** [comment]
@vito +1
(or +2, 'cause we are pairing)

**Comment by bramswenson** [comment]
@vito I concur that hard to diagnose network issues are likely the cause of these types of issues. During initial configuration of concourse I encountered this error on every attempt to `fly execute`. In this case it was a very consistent firewall issue, as in the port to concourse was blocked :small_airplane: I was able to resolve the issue with little issue. However, the error returned wasn't very intuitive. I suggest a different behavior in the face of errors:

  1. Retry x times to upload the context (possibly a flag to `fly execute`)
  1. Have the error message issue a notice about the likelyhood of network issues being the root cause

**Comment by kojisaiki** [comment]
I got same error at trying https://github.com/starkandwayne/concourse-tutorial#02---task-inputs .
I setting up by using docker-compose, too.

- docker-compose.yml
```
concourse-db:
  image: postgres:9.6
  environment:
    POSTGRES_DB: concourse
    POSTGRES_USER: concourse
    POSTGRES_PASSWORD: changeme
    PGDATA: /database
  volumes:
    - /home/concourse/db/database:/database

concourse-web:
  image: concourse/concourse
  links: [concourse-db]
  command: web
  ports: ["8084:8080"]
  volumes: ["./keys/web:/concourse-keys"]
  environment:
    CONCOURSE_BASIC_AUTH_USERNAME: concourse
    CONCOURSE_BASIC_AUTH_PASSWORD: changeme
    CONCOURSE_EXTERNAL_URL: "http://172.19.1.12:8084"
    CONCOURSE_POSTGRES_DATA_SOURCE: |-
      postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable

concourse-worker:
  image: concourse/concourse
  privileged: true
  links: [concourse-web]
  command: worker
  volumes: ["./keys/worker:/concourse-keys"]
  environment:
    CONCOURSE_TSA_HOST: concourse-web
    http_proxy: ##proxy server's host##
    https_proxy: ##proxy server's host##
```

- occured error
```
C:\Users\........\concourse-tutorial\02_task_inputs>fly -t lite execute --config inputs_required.yml --input some-important-input=.
executing build 40
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4052  100  4052    0     0   9611      0 --:--:-- --:--:-- --:--:--  9624
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
exit status 2
[31mfailed[0m
```
