### ISSUE TITLE
inconsistent resources order returned by get-pipeline command

### ISSUE THREAD

**Issue by alpha-er** [concourse/fly#241]
fly version: 3.14.1

For example, first run of `fly get-pipeline -p mypipeline` returns:
```
...
resources:
- name: a
  type: git
- name: b
  type: docker-image
- name: c
  type: git
...
```
The next run may return:
```
...
resources:
- name: c
  type: git
- name: a
  type: git
- name: b
  type: docker-image
...
```
Affects concourse-pipeline-resource `check` command (concourse/concourse-pipeline-resource#38)
