### ISSUE TITLE
fly execute cannot find build inputs on a job that hasn't been ran

### ISSUE THREAD

**Issue by browne0** [concourse/fly#268]
## Problem
I tried to run a fly execute command with some AWS creds, and fly returned back build inputs not found.

All of my files were committed, yet the command still failed.

FLY VERSION: v4.1.0
CREDHUB: v2.0.3
Concourse VM: stemcell bosh-aws-xen-hvm-ubuntu-xenial-go_agent 97.22

## What I expected to happen
fly would execute a command with build inputs locally even if a job hasn't been ran yet

### deployment yaml file with credentials
```yaml
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: meetup/node-awscli
    tag: 'latest'

inputs:
- name: events-proxy-repo

params:
  AWS_ACCESS_KEY_ID: ((aws_access_key_id))
  AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
  AWS_DEFAULT_REGION: ((aws_default_region))

run:
  path: events-proxy-repo/packages/events-proxy/ci/scripts/deploy.sh
```

### failing job in the pipeline

```yaml
- name: events-proxy-lambda-deploy
  plan:
  - get: events-proxy-repo
    trigger: true
    passed:
    - events-proxy-lambda-test
  - task: deploy
    file: events-proxy-repo/packages/events-proxy/ci/tasks/deploy.yml
```

Any guidance or help with this would be appreciated! Thank you for your time 😄
