### ISSUE TITLE
add `fly containers` command

### ISSUE THREAD

**Issue by robdimsdale** [concourse/fly#28]
Given that we have `/api/v1/containers` endpoint, it would be helpful if fly could get a `containers` command. For example this could render (at a minimum):

```
containers:
- handle: handle1
  workerName: worker1
  type: Check
- handle: handle2
  workerName: worker1
  type: Get
- handle: handle3
  workerName: worker1
  type: Task
```
