### ISSUE TITLE
`fly set-pipeline` shows diff when integers are used in pipeline YAML

### ISSUE THREAD

**Issue by jtarchie** [concourse/fly#48]
Given the following `test.yml` pipeline manifest

```yaml
---
resources:
  - name: test
    type: git

jobs:
  - name: test
    plan:
      - put: test
        params:
          test: 1234567890
```

When I successfully `fly set-pipeline -p test -c test.yml`,
When `fly set-pipeline -p test -c test.yml` again,
Then I see the following output

```sh
$ fly -t buildpacks sp -p test -c test.yml
resources:
  resource test has been added:
    name: test
    type: git
    source: {}

jobs:
  job test has changed:
    name: test
    plan:
    - put: test
      params:
        test: 1234567890

apply configuration? [yN]: y
configuration updated

$ fly -t buildpacks sp -p test -c test.yml
resources:
  resource test has changed:
    name: test
    type: git
    source: {}

jobs:
  job test has changed:
    name: test
    plan:
    - put: test
      params:
        test: 1.234568e+09
        test: 1234567890
apply configuration? [yN]:
```

I was expecting there would be no changes to apply to the configuration.
