### ISSUE TITLE
Variables get interpolated as quoted strings

### ISSUE THREAD

**Issue by aequitas** [concourse/fly#53]
When interpolation variables in a string like so:

```
resources:
    - name: test
      type: test
      source:
          uri: http://{{user}}:{{password}}@hostname
```

Fly adds quotes around the values:

```
~/Projects/concourse❯ fly set-pipeline -p test -c test.yaml --var user=test --var password=password

resources:
  resource test has been added:
    name: test
    type: test
    source:
      uri: http://"test":"password"@hostname
```

While my expected output would be:

```
~/Projects/concourse❯ fly set-pipeline -p test -c test.yaml --var user=test --var password=password

resources:
  resource test has been added:
    name: test
    type: test
    source:
      uri: http://test:password@hostname
```

I don't know if this is expected behaviour. Would be nice to use the templating system this way.
