### ISSUE TITLE
hijack presents one option if 2 tasks are named the same

### ISSUE THREAD

**Issue by tobocop** [concourse/fly#56]
When creating a test pipeline I added two tasks with the same name in a single job. When I hijacked in I was presented with only one of the steps and I'm not sure how fly chose which one to use. The fix is likely to, not name 2 things the same, but seems like it's worth bringing up. Example yml:

```
      - task: some-task
        config:
          platform: linux
          run:
            path: sh
            args:
            - -c
            - echo "things"
      - task: some-task
        config:
          platform: linux
          run:
            path: sh
            args:
            - -c
            - echo "other-things"
```

The fly hijack helper only outputs a single task named some-task.
